<a href="https://colab.research.google.com/github/cku7808/Linear-Algebra-Study/blob/main/%EC%84%A0%ED%98%95%EB%B0%A9%EC%A0%95%EC%8B%9D%EA%B3%BC_%EC%84%A0%ED%98%95%EC%8B%9C%EC%8A%A4%ED%85%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **220905 선형대수 강의 실습**

# 선형대수의 기초

In [1]:
import numpy as np

$ n\times1 $의 행렬을 column vector라고 하고 row vector는 column vector에 transpose 취한 행렬이다

In [2]:
# column vector 생성
c = np.array([1,2,3])
print(c.shape)

# 원소 접근
print(c[1])

(3,)
2


In [3]:
# row vector 생성
r = np.array([[1,2,3]])
print(r.shape)

# 원소 접근
print(r[0,1])

(1, 3)
2


In [4]:
# 0으로 구성된 2x2 행렬
a = np.zeros((2,2))
print(a)

# 1으로 구성된 2x2 행렬
b = np.ones((2,2))
print(b)

# 특정 값으로 구성된 2x2 행렬
c = np.full((2,2),5)
print(c)

# 랜덤 값으로 구성된 2x2 행렬
d = np.random.random((2,2))
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[5 5]
 [5 5]]
[[0.46898855 0.34993121]
 [0.094716   0.21122027]]


In [5]:
# 행렬 A 생성
A = np.array([[1,2],[3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
# 행렬 B 생성
B = np.array([[11,12,13,14],[15,16,17,18]])
print(B)

[[11 12 13 14]
 [15 16 17 18]]


In [7]:
# 행렬 A의 transpose
A.T

array([[1, 3, 5],
       [2, 4, 6]])

행렬의 곱(dot product) A*B을 수행하기 위해서는 A의 column 개수 == B의 row 개수여야한다

In [8]:
# 행렬곱
np.dot(A,B)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

# 선형 방정식과 선형 시스템

$a_1x_1 + a_2x_2 + a_3x_3 = b$
의 형태를 띤 방정식을 선형 방정식이라 하고,  
$a_1,a_2,a_3$을 계수라 한다.

$60x_1 + 5.5x_2 + 1x_3 = 66$  
$65x_1 + 5.0x_2 + 0x_3 = 74$  
$55x_1 + 6.0x_2 + 1x_3 = 78$  
위 세 선형 방정식을 만족하는 가중치 $x_1,x_2,x_3$을 구하고자 한다

1. 계수 a로 이루어진 행렬 A를 구성  
$A=\begin{bmatrix}
60 & 5.5 & 1\\
65 & 5.0 & 0\\
55 & 6.0 & 1
\end{bmatrix}
$  
2. 벡터 x와 벡터 b를 구성  
$x=\begin{bmatrix}
x_1\\
x_2\\
x_3
\end{bmatrix}
$ 
$b=\begin{bmatrix}
66\\
74\\
78
\end{bmatrix}
$

위의 세 선형방정식은 다음과 같이 표현될 수 있다.  
$Ax = b$  
$\begin{bmatrix}
60 & 5.5 & 1\\
65 & 5.0 & 0\\
55 & 6.0 & 1
\end{bmatrix}$
$\begin{bmatrix}
x_1\\
x_2\\
x_3
\end{bmatrix}
$
$=\begin{bmatrix}
66\\
74\\
78
\end{bmatrix}
$  \\
또한 다음과 같이 표현할 수도 있다.  
$a^T_1x = 66$  
$a^T_2x = 74$  
$a^T_3x = 78$


In [9]:
A = np.array([[60,5.5,1],[65,5.0,0],[55,6.0,1]])
b = np.array([66,70,78])

In [10]:
# 3x3 항등행렬 생성
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

$x$는 $A$의 역행렬을 구함으로써 구할 수 있다.  
$AA^{-1} = A^{-1}A = l_n$  
양변에 $A^{-1}$을 곱해 $x$를 계산한다  
$(1)\quad A^{-1}Ax = bA^{-1}$  
$(2)\quad x = bA^{-1}$

In [11]:
# 행렬 A의 역행렬 구하기
from numpy.linalg import inv
A_inv = inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [12]:
A.dot(A_inv)

array([[ 1.0000000e+00,  0.0000000e+00, -4.4408921e-16],
       [ 8.8817842e-16,  1.0000000e+00, -8.8817842e-16],
       [-8.8817842e-16,  0.0000000e+00,  1.0000000e+00]])

In [13]:
# x 구하기 - 방법1
x = A_inv.dot(b)
x

array([ -0.43478261,  19.65217391, -16.        ])

In [15]:
# x 구하기 - 방법2
from numpy.linalg import solve
x = solve(A,b)
x

array([ -0.43478261,  19.65217391, -16.        ])